<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="14524" started-at="2018-10-21T17:20:35Z" finished-at="2018-10-21T17:20:49Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="14524" started-at="2018-10-21T17:20:35Z" finished-at="2018-10-21T17:20:49Z">
      <class name="pack1.Testclass">
        <test-method status="PASS" signature="setUp()[pri:0, instance:pack1.Testclass@4cc0edeb]" name="setUp" is-config="true" duration-ms="519" started-at="2018-10-21T05:20:35Z" finished-at="2018-10-21T05:20:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="Sucessfullogin()[pri:1, instance:pack1.Testclass@4cc0edeb]" name="Sucessfullogin" duration-ms="13912" started-at="2018-10-21T05:20:35Z" finished-at="2018-10-21T05:20:49Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at pack1.Testclass.Sucessfullogin(Testclass.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Sucessfullogin -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:pack1.Testclass@4cc0edeb]" name="getResult" is-config="true" duration-ms="23" started-at="2018-10-21T05:20:49Z" finished-at="2018-10-21T05:20:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Sucessfullogin status=FAILURE method=Testclass.Sucessfullogin()[pri:1, instance:pack1.Testclass@4cc0edeb] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="functionality1Test3()[pri:3, instance:pack1.Testclass@4cc0edeb]" name="functionality1Test3" duration-ms="6" started-at="2018-10-21T05:20:49Z" finished-at="2018-10-21T05:20:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- functionality1Test3 -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:pack1.Testclass@4cc0edeb]" name="getResult" is-config="true" duration-ms="2" started-at="2018-10-21T05:20:49Z" finished-at="2018-10-21T05:20:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=functionality1Test3 status=SUCCESS method=Testclass.functionality1Test3()[pri:3, instance:pack1.Testclass@4cc0edeb] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:pack1.Testclass@4cc0edeb]" name="tearDown" is-config="true" duration-ms="1198" started-at="2018-10-21T05:20:49Z" finished-at="2018-10-21T05:20:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- pack1.Testclass -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
